name: CI

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [21]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build project
      run: mvn clean compile
      
    - name: Run tests
      run: mvn test
      
    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Results - ${{ matrix.os }}
        path: target/surefire-reports/*.xml
        reporter: java-junit
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.os }}-java${{ matrix.java }}
        path: target/surefire-reports/
        
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Check compilation warnings
      run: |
        # Compile and capture output
        # Note: We exclude "using incubating module" warnings because the Vector API
        # (jdk.incubator.vector) is an incubating module and will always produce these
        # warnings until it's finalized in a future JDK release
        mvn clean compile -Dmaven.compiler.showWarnings=true 2>&1 | tee compile.log
        
        # Check for warnings other than incubating module warnings
        # Filter out:
        # - "using incubating module" warnings from the Vector API
        # - Maven's own warnings (sun.misc.Unsafe from Maven plugins)
        # - [INFO] lines that contain the word WARNING
        if grep -E "^\[WARNING\]" compile.log | grep -v "using incubating module" | grep -v "sun.misc.Unsafe" | grep -v "A terminally deprecated method" > /dev/null; then
          echo "Found compilation warnings (excluding incubating module and Maven plugin warnings):"
          grep -E "^\[WARNING\]" compile.log | grep -v "using incubating module" | grep -v "sun.misc.Unsafe"
          exit 1
        else
          echo "No significant compilation warnings found (incubating module warnings are expected)"
        fi
        
    - name: Verify no unused dependencies
      run: mvn dependency:analyze
      
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Run integration tests
      run: mvn test -Dtest="*IntegrationTest,*IT"
      
    - name: Run stress tests (if enabled)
      run: mvn test -Dtest="StressTest" -Dstress.tests.enabled=false || true